export default [
  { value: 'CN', text: '中国' },
  { value: 'HK', text: '中国香港' },
  { value: 'TW', text: '中國臺灣' },
  { value: 'US', text: '美国' },
  { value: 'AX', text: 'Åland' },
  { value: 'ME', text: 'Montenegro' },
  { value: 'RS', text: 'Serbia' },
  { value: 'MO', text: 'Macau' },
  { value: 'AG', text: 'Antigua and Barbuda' },
  { value: 'AF', text: 'Afghanistan' },
  { value: 'AZ', text: 'Azerbaijan' },
  { value: 'AW', text: 'Aruba' },
  { value: 'AE', text: 'الامارات' },
  { value: 'AM', text: 'Armenia' },
  { value: 'AO', text: 'Angola' },
  { value: 'AD', text: 'Andorra' },
  { value: 'AI', text: 'Anguilla' },
  { value: 'BB', text: 'Barbados' },
  { value: 'BM', text: 'Bermuda' },
  { value: 'BW', text: 'Botswana' },
  { value: 'BS', text: 'The Bahamas' },
  { value: 'DZ', text: 'Algeria' },
  { value: 'AL', text: 'Shqipëri' },
  { value: 'BZ', text: 'Belize' },
  { value: 'AR', text: 'Argentina' },
  { value: 'BA', text: 'Bosna i Hercegovina' },
  { value: 'SB', text: 'Solomon Islands' },
  { value: 'BR', text: 'Brasil' },
  { value: 'AS', text: 'American Samoa' },
  { value: 'BY', text: 'Belarus' },
  { value: 'AU', text: 'Australia' },
  { value: 'AT', text: 'Österreich' },
  { value: 'BG', text: 'Bulgaria' },
  { value: 'BH', text: 'البحرين' },
  { value: 'CG', text: 'Congo' },
  { value: 'BE', text: 'België' },
  { value: 'BD', text: 'Bangladesh' },
  { value: 'LK', text: 'Sri Lanka' },
  { value: 'BO', text: 'Bolivia' },
  { value: 'BJ', text: 'Benin' },
  { value: 'CC', text: 'Cocos (Keeling) Islands' },
  { value: 'MM', text: 'Myanmar' },
  { value: 'KY', text: 'Cayman Islands' },
  { value: 'BT', text: 'Bhutan' },
  { value: 'CM', text: 'Cameroon' },
  { value: 'BN', text: 'Brunei' },
  { value: 'CO', text: 'Colombia' },
  { value: 'CA', text: 'Canada' },
  { value: 'TD', text: 'Chad' },
  { value: 'BI', text: 'Burundi' },
  { value: 'CF', text: 'Central African Republic' },
  { value: 'KH', text: 'Cambodia' },
  { value: 'CD', text: 'Democratic Republic of Congo' },
  { value: 'CV', text: 'Cape Verde' },
  { value: 'DK', text: 'Danmark' },
  { value: 'EC', text: 'Ecuador' },
  { value: 'IE', text: 'Ireland' },
  { value: 'EG', text: 'مصر' },
  { value: 'GQ', text: 'Equatorial Guinea' },
  { value: 'ER', text: 'Eritrea' },
  { value: 'ET', text: 'Ethiopia' },
  { value: 'CZ', text: 'Česká republika' },
  { value: 'FM', text: 'Federated States of Micronesia' },
  { value: 'PF', text: 'French Polynesia' },
  { value: 'FR', text: 'France' },
  { value: 'CL', text: 'Chile' },
  { value: 'GA', text: 'Gabon' },
  { value: 'GE', text: 'Georgia' },
  { value: 'KM', text: 'Comoros' },
  { value: 'MP', text: 'Northern Mariana Islands' },
  { value: 'GD', text: 'Grenada' },
  { value: 'CR', text: 'Costa Rica' },
  { value: 'GL', text: 'Greenland' },
  { value: 'CU', text: 'Cuba' },
  { value: 'CK', text: 'Cook Islands' },
  { value: 'GU', text: 'Guam' },
  { value: 'GT', text: 'Guatemala' },
  { value: 'GY', text: 'Guyana' },
  { value: 'DJ', text: 'Djibouti' },
  { value: 'GR', text: 'Ellás' },
  { value: 'DM', text: 'Dominica' },
  { value: 'DO', text: 'Dominican Republic' },
  { value: 'EE', text: 'Eesti' },
  { value: 'SV', text: 'El Salvador' },
  { value: 'GF', text: 'Guyane Française' },
  { value: 'FJ', text: 'Fiji' },
  { value: 'FI', text: 'Suomi' },
  { value: 'FK', text: 'Falkland Islands' },
  { value: 'FO', text: 'Føroyar' },
  { value: 'GM', text: 'The Gambia' },
  { value: 'GH', text: 'Ghana' },
  { value: 'GI', text: 'Gibraltar' },
  { value: 'DE', text: 'Deutschland' },
  { value: 'GP', text: 'Guadeloupe' },
  { value: 'GN', text: 'Guinea' },
  { value: 'HN', text: 'Honduras' },
  { value: 'IS', text: 'Ísland' },
  { value: 'HT', text: 'Haiti' },
  { value: 'HU', text: 'Magyarország' },
  { value: 'IO', text: 'British Indian Ocean Territory' },
  { value: 'IT', text: 'Italia' },
  { value: 'CI', text: 'Côte d´Ivoire' },
  { value: 'JM', text: 'Jamaica' },
  { value: 'KP', text: 'North Korea' },
  { value: 'JO', text: 'الأردن' },
  { value: 'KZ', text: 'Kazakhstan' },
  { value: 'LB', text: 'لبنان' },
  { value: 'KR', text: '한국' },
  { value: 'KW', text: 'الكويت' },
  { value: 'LA', text: 'Laos' },
  { value: 'LR', text: 'Liberia' },
  { value: 'LS', text: 'Lesotho' },
  { value: 'MG', text: 'Madagascar' },
  { value: 'LY', text: 'Libya' },
  { value: 'HR', text: 'Hrvatska' },
  { value: 'MW', text: 'Malawi' },
  { value: 'ML', text: 'Mali' },
  { value: 'ID', text: 'Republik Indonesia' },
  { value: 'MA', text: 'المغرب' },
  { value: 'MT', text: 'Malta' },
  { value: 'MU', text: 'Mauritius' },
  { value: 'MY', text: 'Malaysia' },
  { value: 'NC', text: 'New Caledonia' },
  { value: 'VU', text: 'Vanuatu' },
  { value: 'NL', text: 'Nederland' },
  { value: 'NP', text: 'Nepal' },
  { value: 'SR', text: 'Suriname' },
  { value: 'NZ', text: 'New Zealand' },
  { value: 'NG', text: 'Nigeria' },
  { value: 'PN', text: 'Pitcairn Islands' },
  { value: 'IR', text: 'Iran' },
  { value: 'IN', text: 'India' },
  { value: 'IL', text: 'Israel' },
  { value: 'IQ', text: 'Iraq' },
  { value: 'JP', text: '日本' },
  { value: 'KE', text: 'Kenya' },
  { value: 'KI', text: 'Kiribati' },
  { value: 'CX', text: 'Christmas Island' },
  { value: 'KG', text: 'Kyrgyzstan' },
  { value: 'LT', text: 'Lietuva' },
  { value: 'SK', text: 'Slovenská' },
  { value: 'LI', text: 'Liechtenstein' },
  { value: 'LV', text: 'Latvija' },
  { value: 'LU', text: 'Luxembourg' },
  { value: 'MD', text: 'Moldova' },
  { value: 'MN', text: 'Mongolia' },
  { value: 'MQ', text: 'Martinique' },
  { value: 'YT', text: 'Mayotte' },
  { value: 'MS', text: 'Montserrat' },
  { value: 'MK', text: 'Macedonia' },
  { value: 'MC', text: 'Monaco' },
  { value: 'MV', text: 'Maldives' },
  { value: 'MR', text: 'Mauritania' },
  { value: 'NF', text: 'Norfolk Island' },
  { value: 'OM', text: 'عمان' },
  { value: 'MX', text: 'México' },
  { value: 'PK', text: 'Pakistan' },
  { value: 'MZ', text: 'Mozambique' },
  { value: 'PA', text: 'Panamá' },
  { value: 'NU', text: 'Niue' },
  { value: 'PG', text: 'Papua New Guinea' },
  { value: 'NE', text: 'Niger' },
  { value: 'NO', text: 'Norge' },
  { value: 'QA', text: 'قطر' },
  { value: 'NR', text: 'Nauru' },
  { value: 'PH', text: 'Philippines' },
  { value: 'NI', text: 'Nicaragua' },
  { value: 'PY', text: 'Paraguay' },
  { value: 'SA', text: 'السعودية' },
  { value: 'PE', text: 'Peru' },
  { value: 'PL', text: 'Polska' },
  { value: 'XX', text: 'Disputed Territory' },
  { value: 'PW', text: 'Palau' },
  { value: 'MH', text: 'Marshall Islands' },
  { value: 'RE', text: 'La Réunion' },
  { value: 'RU', text: 'Russia' },
  { value: 'PR', text: 'Puerto Rico' },
  { value: 'PM', text: 'Saint Pierre and Miquelon' },
  { value: 'XS', text: 'Spratly Islands' },
  { value: 'PT', text: 'Portugal' },
  { value: 'GW', text: 'Guinea-Bissau' },
  { value: 'RO', text: 'România' },
  { value: 'RW', text: 'Rwanda' },
  { value: 'KN', text: 'Saint Kitts and Nevis' },
  { value: 'SN', text: 'Sénégal' },
  { value: 'SM', text: 'San Marino' },
  { value: 'LC', text: 'St. Lucia' },
  { value: 'GS', text: 'South Georgia and the South Sandwich Islands' },
  { value: 'TK', text: 'Tokelau' },
  { value: 'SH', text: 'St Helena Ascension and Tristan da Cunha' },
  { value: 'TN', text: 'Tunisia' },
  { value: 'SL', text: 'Sierra Leone' },
  { value: 'ES', text: 'España' },
  { value: 'SC', text: 'Seychelles' },
  { value: 'SI', text: 'Slovenija' },
  { value: 'SO', text: 'Somalia' },
  { value: 'CH', text: 'Schweiz' },
  { value: 'TJ', text: 'Tajikistan' },
  { value: 'SD', text: 'Sudan' },
  { value: 'SY', text: 'Syria' },
  { value: 'TT', text: 'Trinidad and Tobago' },
  { value: 'TC', text: 'Turks and Caicos Islands' },
  { value: 'TO', text: 'Tonga' },
  { value: 'ZA', text: 'South Africa' },
  { value: 'TG', text: 'Togo' },
  { value: 'TR', text: 'Turkey' },
  { value: 'SG', text: 'Singapore' },
  { value: 'SE', text: 'Sverige' },
  { value: 'TZ', text: 'Tanzania' },
  { value: 'TH', text: 'Thailand' },
  { value: 'GB', text: 'United Kingdom' },
  { value: 'US', text: 'United States' },
  { value: 'UY', text: 'Uruguay' },
  { value: 'VG', text: 'British Virgin Islands' },
  { value: 'VI', text: 'US Virgin Islands' },
  { value: 'NA', text: 'Namibia' },
  { value: 'WF', text: 'Wallis and Futuna' },
  { value: 'UA', text: 'Ukrayina' },
  { value: 'VE', text: 'Venezuela' },
  { value: 'VA', text: 'Città del Vaticano' },
  { value: 'XE', text: 'Iraq-Saudi Arabia Neutral Zone' },
  { value: 'ZM', text: 'Zambia' },
  { value: 'WS', text: 'Samoa' },
  { value: 'ST', text: 'Sao Tome and Principe' },
  { value: 'VC', text: 'Saint Vincent and the Grenadines' },
  { value: 'TL', text: 'Timor-Leste' },
  { value: 'TV', text: 'Tuvalu' },
  { value: 'TM', text: 'Turkmenistan' },
  { value: 'UG', text: 'Uganda' },
  { value: 'BF', text: 'Burkina Faso' },
  { value: 'UZ', text: 'Uzbekistan' },
  { value: 'VN', text: 'Vietnam' },
  { value: 'SZ', text: 'Swaziland' },
  { value: 'EH', text: 'Western Sahara' },
  { value: 'XD', text: 'United Nations Neutral Zone' },
  { value: 'YE', text: 'Yemen' },
  { value: 'ZW', text: 'Zimbabwe' },
  { value: 'CY', text: 'Cyprus' },
  { value: 'UM', text: 'United States Minor Outlying Islands' },
  { value: 'HM', text: 'Heard Island and McDonald Islands' },
  { value: 'SJ', text: 'Svalbard and Jan Mayen' },
  { value: 'AQ', text: 'Antarctica' },
  { value: 'TF', text: 'French Southern Territories' },
  { value: 'PS', text: 'Palestine' },
  { value: 'BV', text: 'Bouvet Island' },
  { value: 'MF', text: 'Saint-Martin' },
  { value: 'BL', text: 'Saint-Barthélemy' },
  { value: 'BQ', text: 'Bonaire Saint Eustatius and Saba' },
  { value: 'SS', text: 'The Republic of South Sudan' },
  { value: 'CW', text: 'Curaçao' },
  { value: 'SX', text: 'Sint Maarten' },
  { value: 'DE', text: '德国' },
];
